// <auto-generated />
namespace StarterKITDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class initial_details : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_details));
        
        string IMigrationMetadata.Id
        {
            get { return "202210251622068_initial_details"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
